cd ..
mv -r DM src/DM
mv -r bin src/bin
mv -r bridge src/bridge
mv -r camera src/camera
mv -r gellotest src/gellotest
mv -r hank src/hank
mv -r logs src/logs
mv -r magtest src/magtest
mv -r public src/public
mv -r save-data-from-db src/save-data-from-db
mv -r scripts src/scripts
mv -r strain src/strain
mv -r stubbyhank src/stubbyhank
mv -r web src/web
mv -r www/static src/www/static
mv -r .gitignore src/.gitignore
mv -r README.md src/README.md
mv -r changelog.md src/changelog.md
mv -r logall src/logall
mv -r makefile src/makefile
mv -r rtunnel.sh src/rtunnel.sh
mv -r server-configuration-notes src/server-configuration-notes
mv -r start-app.sh src/start-app.sh
mv -r test.txt src/test.txt
