version: "3"

services:
  db:
    image: mysql:5
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - data:/var/lib/mysql
    networks:
      - main
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3300:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - main

networks:
  main:
volumes:
  data:
