const { Router, static } = require('express')
const { join } = require('path')
const authRouter = require('./auth')
const databaseRouter = require('./database')
const devicesRouter = require('./devices')
const { verifyToken } = require('../utils/auth')

module.exports = Router()
  .use('/auth', authRouter)
  .use(verifyToken(false))
  .use('/static', static(join(__dirname, '..', 'static')))
  .use('/database', databaseRouter)
  .use('/devices', verifyToken(true), devicesRouter)
